Update test cases (#104)
- Uses new ecephys H5, Zarr, and LINDI files
- Points to ophys files
- Points to icephys files
- Disables other files
- Extracted file read parameter cases and slicing parameter cases into
their own files because the test cases should be the same.

The benchmarks are not totally consistent between time_read and
network_tracking. That should be handled in a separate PR.

Zarr tests are failing (`TypeError: ClientSession._request() got an
unexpected keyword argument 'anon'`) and will be handled separately.

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>